create table
  public.cart_items (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    cart_id integer null,
    potion_id integer null,
    quantity integer null,
    sku text null,
    constraint cart_items_pkey primary key (id)
  ) tablespace pg_default;

  create table
  public.carts (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    customer text null,
    constraint carts_pkey primary key (id)
  ) tablespace pg_default;

  create table
  public.global_inventory (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    num_red_ml integer null,
    gold integer null,
    num_green_ml integer null,
    num_blue_ml integer null,
    num_dark_ml integer null default 0,
    constraint global_inventory_pkey primary key (id)
  ) tablespace pg_default;

  create table
  public.potions (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    sku text null,
    potion_type integer[] null default '{0,0,0,0}'::integer[],
    inventory integer null default 0,
    cost integer null default 50,
    constraint potions_pkey primary key (id)
  ) tablespace pg_default;